/******************************************************************************
 * Copyright 2015 Specialized Solutions LLC
 *
 * Title to the Materials (contents of this file) remain with Specialized
 * Solutions LLC.  The Materials are copyrighted and are protected by United
 * States copyright laws.  Copyright notices cannot be removed from the
 * Materials.
 *
 * @brief QCM Default Include File
 *
 *****************************************************************************/
 
#pragma amxlimit 65524 /* ~64 kiB available for code */
#pragma amxram 20480 /* 20 kiB available for data + stack */

#include <core>
#include <console>
#include <float>
#include <string>
#include <qcm_bdg>

